"""argparse construction for the commands that edit a strip or move a preset around —
presentation. One file per command family, as _parsers_live.py is for the live desk."""

from __future__ import annotations

from .services.scopes import SCOPES


def _add_edits(sub, _out, _strip_arg) -> None:
    s = sub.add_parser("extract-preset", help="one channel as a channel preset (.chn)")
    s.add_argument("scene")
    s.add_argument("ch", type=int)
    _out(s)
    s.add_argument("--scope", action="append", choices=SCOPES,
                   help="limit to these scopes (repeatable); default = all")
    s.add_argument("--header", action="store_true",
                   help="write a #4.0# header naming the preset after the channel "
                        "(opt-in: the flag bit order is inferred, LOAD-TEST it)")
    s = sub.add_parser("apply-preset", help="load a channel preset (.chn) onto a channel")
    s.add_argument("scene")
    s.add_argument("ch", type=int)
    s.add_argument("preset")
    _out(s)
    s.add_argument("--scope", action="append", choices=SCOPES)
    nolink_help = "edit only this strip, even on a stereo-linked pair"
    s = sub.add_parser("set-eq", help="set an EQ band: type, frequency, gain, Q")
    s.add_argument("scene")
    s.add_argument("strip", type=_strip_arg)
    s.add_argument("band", type=int)
    _out(s)
    s.add_argument("--type")
    s.add_argument("--freq", type=float)
    s.add_argument("--gain", type=float)
    s.add_argument("--q", type=float)
    s.add_argument("--no-link", action="store_true", help=nolink_help)
    # knobs: the flags _require_a_knob demands at least one of (flag -> args dest)
    s.set_defaults(knobs={"--type": "type", "--freq": "freq", "--gain": "gain", "--q": "q"})
    s = sub.add_parser("set-comp", help="set the compressor: threshold, ratio, makeup, attack, release")
    s.add_argument("scene")
    s.add_argument("strip", type=_strip_arg)
    _out(s)
    s.add_argument("--thr", type=float)
    s.add_argument("--ratio")
    s.add_argument("--makeup", type=float)
    s.add_argument("--attack", type=float)
    s.add_argument("--release", type=float)
    s.add_argument("--no-link", action="store_true", help=nolink_help)
    s.set_defaults(knobs={"--thr": "thr", "--ratio": "ratio", "--makeup": "makeup",
                          "--attack": "attack", "--release": "release"})
    s = sub.add_parser("set-gate", help="set the gate: threshold, range, attack, release")
    s.add_argument("scene")
    s.add_argument("strip", type=_strip_arg)
    _out(s)
    s.add_argument("--thr", type=float)
    s.add_argument("--range", type=float, dest="rng")
    s.add_argument("--attack", type=float)
    s.add_argument("--release", type=float)
    s.add_argument("--no-link", action="store_true", help=nolink_help)
    s.set_defaults(knobs={"--thr": "thr", "--range": "rng", "--attack": "attack",
                          "--release": "release"})
    s = sub.add_parser("set-lowcut", help="switch a strip's low cut on/off and set its frequency")
    s.add_argument("scene")
    s.add_argument("strip", type=_strip_arg)
    _out(s)
    onoff = s.add_mutually_exclusive_group()
    onoff.add_argument("--on", action="store_true")
    onoff.add_argument("--off", action="store_true")
    s.add_argument("--freq", type=float)
    s.add_argument("--no-link", action="store_true", help=nolink_help)
    s.set_defaults(knobs={"--on": "on", "--off": "off", "--freq": "freq"})
    s = sub.add_parser("set-fader",
                       help="set a strip's fader level (dB, or oo for -infinity)")
    s.add_argument("scene")
    s.add_argument("strip", type=_strip_arg)
    s.add_argument("level", help="dB, or oo (also -oo) for -infinity")
    _out(s)
    s.add_argument("--no-link", action="store_true", help=nolink_help)
    s = sub.add_parser("set-mute", help="mute/unmute a strip")
    s.add_argument("scene")
    s.add_argument("strip", type=_strip_arg)
    s.add_argument("state", choices=["on", "off"], help="on = muted")
    _out(s)
    s.add_argument("--no-link", action="store_true", help=nolink_help)
    s = sub.add_parser("set-pan", help="set a strip's pan/balance (-100..+100)")
    s.add_argument("scene")
    s.add_argument("strip", type=_strip_arg)
    s.add_argument("pan", type=int, help="-100 (L) .. +100 (R)")
    _out(s)
    s = sub.add_parser("rename", help="rename a strip (channel, bus, DCA, etc.)")
    s.add_argument("scene")
    s.add_argument("strip", type=_strip_arg)
    s.add_argument("name")
    _out(s)
